package airline.connector.impl;

import airline.connector.Connector;
import static airline.model.Transaction.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Implementation of the connector
 */
public class ConnectorImpl implements Connector {
    private Connection connection;

    public ConnectorImpl() {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            //connection = DriverManager.getConnection("jdbc:hsqldb:file:forumBDD;shutdown=true", "sa", "");
            connection = DriverManager.getConnection("jdbc:hsqldb:mem:forumBDD", "sa", "");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Error while setting the SQL connection");
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public void initSchema() throws SQLException {
        Statement statement = connection.createStatement();
        statement.executeUpdate(
                String.format("CREATE TABLE %s(%s INT  GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY," +
                        "%s TIMESTAMP NULL," +
                        "%s VARCHAR(250) NULL);", TRANSACTION_TABLE, IDENTIFIANT, TIME, DESCRIPTION)
        );
    }

    public void fillTables() throws SQLException {
    }

    public void dropTables() throws SQLException {
    }

    public void disconnect() {
        Statement statement;
        try {
            statement = connection.createStatement();
            statement.executeQuery("SHUTDOWN");
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
