/**
 * Copyright (C) 2009 Anthonin Bonnefoy and David Duponchel
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *         http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package airline.connector.impl;

import airline.connector.Connector;
import static airline.model.Transaction.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Implementation of the connector
 */
public class ConnectorImpl implements Connector {
    private Connection connection;

    public ConnectorImpl() {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            //connection = DriverManager.getConnection("jdbc:hsqldb:file:forumBDD;shutdown=true", "sa", "");
            connection = DriverManager.getConnection("jdbc:hsqldb:file:db/airline", "sa", "");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Error while setting the SQL connection");
        }
        try {
            initSchema();
        } catch (SQLException e) {
            System.out.println("Transaction table already existing");
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public void initSchema() throws SQLException {
        Statement statement = connection.createStatement();
        statement.executeUpdate(
                String.format("CREATE TABLE %s(%s INT  GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY," +
                        "%s TIMESTAMP NULL," +
                        "%s VARCHAR(250) NULL);", TRANSACTION_TABLE, IDENTIFIANT, TIME, DESCRIPTION)
        );
    }

    public void fillTables() throws SQLException {
    }

    public void dropTables() throws SQLException {
    }

    public void disconnect() {
        Statement statement;
        try {
            statement = connection.createStatement();
            statement.executeQuery("SHUTDOWN");
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
