package airline.connector.impl;

import airline.connector.Connector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Implementation of the connector
 */
public class ConnectorImpl implements Connector {
    private Connection connection;

    public ConnectorImpl() {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:file:forumBDD", "sa", "");
            initSchema();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println("Tables already exist");
        }
    }

    public Connection getConnection() {
        return connection;
    }

    public void initSchema() throws SQLException {
        Statement statement = connection.createStatement();
        /*
        statement.executeUpdate(
                "CREATE TABLE user(" +
                        ForumUserEntry.COL_ID_CLIENT + " INT  GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY," +
                        ForumUserEntry.COL_CLIENT_NAME + " VARCHAR(45) NOT NULL," +
                        ForumUserEntry.COL_ENTRY + " TIMESTAMP NULL," +
                        ForumUserEntry.COL_EXIT + " TIMESTAMP NULL);"
        );
        */
    }

    public void disconnect() {
        Statement statement;
        try {
            statement = connection.createStatement();
            statement.executeQuery("SHUTDOWN");
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
